### All the movies
GET https://rest-api-ytw2-dev.fl0.io/movies

### Movie by ID
GET https://rest-api-ytw2-dev.fl0.io/movies/7e3fd5ab-60ff-4ae2-92b6-9597f0308d1

### Movies by genre
GET https://rest-api-ytw2-dev.fl0.io/movies?genre=sci-fi

### Create a Movie with POST
POST https://rest-api-ytw2-dev.fl0.io/movies
Content-Type: application/json

{
  "title": "The shawshank redemption",
  "year": 1994,
  "director": "Daniel Vasquez",
  "duration": 142,
  "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
  "genre": [
    "Drama",
    "Action",
    "Adventure"
  ],
  "rate": 9
}

### Update a movie data
PATCH https://rest-api-ytw2-dev.fl0.io/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "title": "New title",
  "year": 2024
}

### Delete a movie
DELETE https://rest-api-ytw2-dev.fl0.io/movies/9904f816-3b83-4daa-a2b4-4dc4074d81ec